[package]
name = "jessie-entry"
version = "0.1.0"
edition = "2024"

[dependencies]
jessie-ast = { version = "0.1.0", path = "../jessie-ast" }
jessie-ast-lowering = { version = "0.1.0", path = "../jessie-ast-lowering" }
jessie-cratesio = { version = "0.1.0", path = "../jessie-cratesio" }
jessie-session = { version = "0.1.0", path = "../jessie-session" }
jessie-span = { version = "0.1.0", path = "../jessie-span" }
jessie-tokenizer = { version = "0.1.0", path = "../jessie-tokenizer" }
