[package]
name = "jessie-build"
version = "0.1.0"
edition = "2024"
description = "The library that sets up Jessie apps for build."
homepage = "https://jessie.rs"
license = "MIT"
repository = "https://github.com/jessie-framework/jessie"

[dependencies]
