[package]
name = "jessie-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
jessie-ast-lowering = { version = "0.1.0", path = "../jessie-ast-lowering" }
jessie-cratesio = { version = "0.1.0", path = "../jessie-cratesio" }
jessie-span = { version = "0.1.0", path = "../jessie-span" }
jessie-tokenizer = { version = "0.1.0", path = "../jessie-tokenizer" }
syn = { version = "3.0.3", features = ["full", "proc-macro"] }
